name: Test and lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: Run tests

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11-dev"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test typing_extensions
        run: |
          # Be wary of running `pip install` here, since it becomes easy for us to
          # accidentally pick up typing_extensions as installed by a dependency
          cd typing_extensions/src
          python -m unittest test_typing_extensions.py

  linting:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
          cache: "pip"
          cache-dependency-path: "test-requirements.txt"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Lint implementation
        run: flake8

      - name: Lint tests
        run: flake8 --config=.flake8-tests typing_extensions/src/test_typing_extensions.py
