name: Test and lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests-27:
    name: Run tests (2.7)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Run tests
        run: |
          pytest python2
          pip install -U .
          pytest typing_extensions/src_py2

  tests:
    name: Run tests

    strategy:
      fail-fast: false
      matrix:
        # Python 3.4 disabled, due to problems with GitHub Actions.
        python-version: [3.10-dev, 3.9, 3.8, 3.7, 3.6, 3.5]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Test typing
        if: matrix.python-version < '3.7'
        run: pytest src

      - name: Test typing_extensions
        run: pytest typing_extensions/src_py3

  linting:
    name: Run linting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Run linting
        run: |
          flake8
          flake8 --config=.flake8-tests src/test_typing.py python2/test_typing.py typing_extensions/src_py2/test_typing_extensions.py typing_extensions/src_py3/test_typing_extensions.py
